"""initial schema

Revision ID: 3c9b4e331bab
Revises: 
Create Date: 2026-04-17 18:24:30.365532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9b4e331bab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('kalshi_ticker', sa.String(), nullable=True),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'start_ts', name='uq_window_market_start_ts')
    )
    with op.batch_alter_table('windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_windows_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_windows_resolved'), ['resolved'], unique=False)
        batch_op.create_index('ix_windows_start_ts', ['start_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_windows_window_id'), ['window_id'], unique=True)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_fk', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('p_model', sa.Float(), nullable=True),
    sa.Column('p_market', sa.Float(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['window_fk'], ['windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_window_fk'), ['window_fk'], unique=False)

    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_fk', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('return_1m', sa.Float(), nullable=True),
    sa.Column('return_5m', sa.Float(), nullable=True),
    sa.Column('return_15m', sa.Float(), nullable=True),
    sa.Column('realized_vol_60m', sa.Float(), nullable=True),
    sa.Column('atr_percentile', sa.Float(), nullable=True),
    sa.Column('btc_return_5m', sa.Float(), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['window_fk'], ['windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_window_fk'), ['window_fk'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_fk', sa.Integer(), nullable=False),
    sa.Column('kalshi_order_id', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price_cents', sa.Integer(), nullable=False),
    sa.Column('fill_price_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['decision_fk'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_decision_fk'), ['decision_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_kalshi_order_id'), ['kalshi_order_id'], unique=False)
        batch_op.create_index('ix_orders_status', ['status'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_fk', sa.Integer(), nullable=False),
    sa.Column('settlement_price', sa.Float(), nullable=True),
    sa.Column('pnl_cents', sa.Integer(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_fk'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_order_fk'), ['order_fk'], unique=True)
        batch_op.create_index('ix_outcomes_resolved_at', ['resolved_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index('ix_outcomes_resolved_at')
        batch_op.drop_index(batch_op.f('ix_outcomes_order_fk'))

    op.drop_table('outcomes')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_status')
        batch_op.drop_index(batch_op.f('ix_orders_kalshi_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_decision_fk'))

    op.drop_table('orders')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_window_fk'))

    op.drop_table('features')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_window_fk'))

    op.drop_table('decisions')
    with op.batch_alter_table('windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_windows_window_id'))
        batch_op.drop_index('ix_windows_start_ts')
        batch_op.drop_index(batch_op.f('ix_windows_resolved'))
        batch_op.drop_index(batch_op.f('ix_windows_market'))

    op.drop_table('windows')
    # ### end Alembic commands ###
